# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install deps
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pandas ipython coverage
  - source activate test-environment


# command to run tests, e.g. python setup.py test
script:
  - python setup.py test